version: '3.7'
services:
  nginx:
    image: nginx:1.17.9-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    links:
      - swagger-dir
  swagger-dir:
    image: vdustr/swagger-dir:latest
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ../../data/:/data:ro
    command: -u /swagger-dir/ -l 0
